@startuml

title __GAME3's Class Diagram__\n

  namespace com.example.keystone_try {
    namespace game3 {
      class com.example.keystone_try.game3.GameThree {
          + highScore : int
          + score : int
          ~ handler : Handler
          ~ runnable1 : Runnable
          {static} - HIGH_SCORE : String
          - buttons : ImageButton[][]
          - card_images : int[]
          - cards : GameThreeCard[][]
          - clickSoundID : int
          - countDownTimer : CountDownTimer
          - currentcard_x : int
          - currentcard_y : int
          - helpB : Button
          - highScoreTxt : TextView
          - isFirstClick : boolean
          - item_images : int[]
          - item_names : String[]
          - lastcard_x : int
          - lastcard_y : int
          - quantity : int
          - quantityTxt : TextView
          - removeSoundID : int
          - second : int
          - soundPool : SoundPool
          - start : Button
          - startDownTimer : CountDownTimer
          - tableLayout : TableLayout
          - timeTxt : TextView
          - volumnCurrent : float
          - volumnRatio : float
          - winSoundID : int
          + onKeyDown()
          # onCreate()
          - checkOver()
          - getHighScore()
          - getRandomCardNumber()
          - getRandomNumber()
          - initCardPanel()
          - initSound()
          - playSound()
          - recordHighScore()
          - resetTime()
          - showMessage()
          - startCounter()
          - startShowCard()
          - toastShow()
      }
    }
  }
  

  namespace com.example.keystone_try {
    namespace game3 {
      class com.example.keystone_try.game3.GameThree.CardClickListener {
          + onClick()
      }
    }
  }
  

  namespace com.example.keystone_try {
    namespace game3 {
      class com.example.keystone_try.game3.GameThreeCard {
          - image_index : int
          - remove : boolean
          - show : boolean
          - x : int
          - y : int
          + GameThreeCard()
          + getImage_index()
          + getX()
          + getY()
          + isRemove()
          + isShow()
          + setImage_index()
          + setRemove()
          + setShow()
          + setX()
          + setY()
      }
    }
  }
  

  com.example.keystone_try.game3.GameThree -up-|> android.app.Activity
  com.example.keystone_try.game3.GameThree +-down- com.example.keystone_try.game3.GameThree.CardClickListener
  com.example.keystone_try.game3.GameThree.CardClickListener .up.|> android.view.View.OnClickListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
