@startuml

title __UTILS's Class Diagram__\n

  namespace com.example.keystone_try {
    namespace step {
      namespace utils {
        class com.example.keystone_try.step.utils.DbUtils {
            {static} + DB_NAME : String
            {static} + liteOrm : LiteOrm
            {static} + closeDb()
            {static} + createDb()
            {static} + deleteAll()
            {static} + deleteWhere()
            {static} + getLiteOrm()
            {static} + getQueryAll()
            {static} + getQueryByWhere()
            {static} + getQueryByWhereLength()
            {static} + insert()
            {static} + insertAll()
            {static} + update()
            {static} + updateALL()
        }
      }
    }
  }
  

  namespace com.example.keystone_try {
    namespace step {
      namespace utils {
        class com.example.keystone_try.step.utils.SPHelper {
            {static} + JSON_CACHE : String
            {static} + clearPreference()
            {static} + getBoolean()
            {static} + getContent()
            {static} + getFloat()
            {static} + getInt()
            {static} + getJSONCache()
            {static} + getLong()
            {static} + getString()
            {static} + putBoolean()
            {static} + putContent()
            {static} + putFloat()
            {static} + putInt()
            {static} + putJSONCache()
            {static} + putLong()
            {static} + putString()
            {static} + remove()
        }
      }
    }
  }
  

  namespace com.example.keystone_try {
    namespace step {
      namespace utils {
        class com.example.keystone_try.step.utils.StepCountModeDispatcher {
            - context : Context
            - hasSensor : boolean
            + StepCountModeDispatcher()
            + isSupportStepCountSensor()
            {static} + isSupportStepCountSensor()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
