@startuml

title __NOTIFICATIONS's Class Diagram__\n

  namespace com.example.keystone_try {
    namespace ui {
      namespace notifications {
        class com.example.keystone_try.ui.notifications.NotificationsFragment {
            - barChart : BarChart
            - barChartArrayList : ArrayList<BarChart>
            - lineChart : LineChart
            - lineChartArrayList : ArrayList<LineChart>
            - radioGroup : RadioGroup
            + drawBarChart()
            + drawLineChart()
            + getResentData()
            + onCreateView()
            + radioGroupSelected()
            + setBarChartArrayList()
            + setLineChartArrayList()
            + test()
            - text_all()
            - xText()
            - yText()
        }
      }
    }
  }
  

  namespace com.example.keystone_try {
    namespace ui {
      namespace notifications {
        class com.example.keystone_try.ui.notifications.NotificationsFragment.IntegerAxisFormatter {
            + getFormattedValue()
        }
      }
    }
  }
  

  namespace com.example.keystone_try {
    namespace ui {
      namespace notifications {
        class com.example.keystone_try.ui.notifications.NotificationsFragment.MonthlyIntegerYValueFormatter {
            + getFormattedValue()
        }
      }
    }
  }
  

  namespace com.example.keystone_try {
    namespace ui {
      namespace notifications {
        class com.example.keystone_try.ui.notifications.NotificationsFragment.XaxisFormatter {
            + getFormattedValue()
        }
      }
    }
  }
  

  com.example.keystone_try.ui.notifications.NotificationsFragment -up-|> androidx.fragment.app.Fragment
  com.example.keystone_try.ui.notifications.NotificationsFragment +-down- com.example.keystone_try.ui.notifications.NotificationsFragment.IntegerAxisFormatter
  com.example.keystone_try.ui.notifications.NotificationsFragment +-down- com.example.keystone_try.ui.notifications.NotificationsFragment.MonthlyIntegerYValueFormatter
  com.example.keystone_try.ui.notifications.NotificationsFragment +-down- com.example.keystone_try.ui.notifications.NotificationsFragment.XaxisFormatter
  com.example.keystone_try.ui.notifications.NotificationsFragment.IntegerAxisFormatter .up.|> com.github.mikephil.charting.formatter.IAxisValueFormatter
  com.example.keystone_try.ui.notifications.NotificationsFragment.MonthlyIntegerYValueFormatter .up.|> com.github.mikephil.charting.formatter.IValueFormatter
  com.example.keystone_try.ui.notifications.NotificationsFragment.XaxisFormatter .up.|> com.github.mikephil.charting.formatter.IAxisValueFormatter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
